### ISSUE TITLE
Errori durante la compilazione

### ISSUE THREAD

**Issue by DigiOhhh** [prog2-unimi/handouts#1]
Buonasera professore, in qualche commento nei sorgenti della repo sono presenti `unmappable characters in encoding US-ASCII`:

![image](https://user-images.githubusercontent.com/37815914/68407944-b6a81100-0184-11ea-9c3a-00f2e47fa99c.png)

Gli errori si riferiscono ai seguenti caratteri:

- `…`
- `′`

Ho risolto passando il parametro `-encoding UTF-8` a `javac`, ma mi è sembrato il caso di segnalarglielo comunque.

Inoltre il sorgente IntSets.java in `src/it/unimi/di/prog2/l07` importa un pacchetto da `src/it/unimi/di/prog2/l08`, che risultava in un ulteriore errore di compilazione prima del commit 7e652401e9245f9303b36959d54a96aff26aaef1

**Comment by mapio** [comment]
Grazie della segnalazione. 

L'errore di impotazione è legato al fatto che nella lezione 8 è fornita una implementazione per cui le classi che usano insiemi e polinomi devono importare le classi dal pacchetto dove sono importate. Si tratta di una anomalia dovuta alla sequenza con cui sono discussi gli argomenti nel libro di testo. A regime (ossia dopo il commit che ha osservato), l'anomalia è risolta.
